### PR TITLE
DDS-1194 Introduce Changesets

### PR DESCRIPTION
**Pull request by yodas7**
This PR introduces [Changesets](https://github.com/changesets/changesets), a release automation tool.

## Checklist

Before we merge this, we have to setup repo.

- [x] Add `NPM_TOKEN` to the GitHub Actions secrets.
- [x] Remove `main` branch and Rename `develop` to `main` branch.
- [x] ~~Disable automatic deployments on `main` branch.~~  
       No longer needed; see https://github.com/dsv-rp/DDS/pull/31#issuecomment-2251818839.
- [x] ~~Investigate manual deploy command to deploy production storybook site.~~  
       ~~The command should be added to `release.yml`.~~  
       No longer needed; see https://github.com/dsv-rp/DDS/pull/31#issuecomment-2251818839.

## After Checklist

- [ ] Introduce Changesets bot? https://github.com/dsv-rp/DDS/pull/31#issuecomment-2249258278
- [ ] Point to GitHub pages in Zeroheight.

### CODE REVIEW

**Comment by yodas7** [comment]
In my experience, we may need to go through a few trial and error attempts before introducing such automation tools.
After merging this PR, I want to practice releasing the package.

**Review by KoharaKazuya — APPROVED** [review]
@yodas7 
LGTM! I think you should inform all developers that they must add changesets. Could you communicate to them?

**Comment by yodas7** [comment]
I'll do it.

Also, Changesets recommends introducing [a bot that checks whether a PR includes a changeset file](https://github.com/apps/changeset-bot), so I want to ask @hiro-daikin if this can be introduced into the repository.

**Comment by yodas7** [comment]
@hiro-daikin 
At first, I was thinking of stopping Netlify's automatic deployment and deploying from CI.
However, I realized that it would be easier to build a CD if I used Netlify's automatic deployment and made GitHub Pages the production environment.
Therefore, I would like to propose the following:

- Treating Netlify, which is currently treated as a _production_ environment, as a **development** environment
- Treating GitHub Pages, which is currently treated as a _development_ environment, as a **production** environment

**Review by hiro-daikin — APPROVED** [review]

**Pull request merged**
